ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'cajero';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'oficina';

ALTER TABLE "usuario"
ADD COLUMN IF NOT EXISTS "nombre" TEXT,
ADD COLUMN IF NOT EXISTS "email" TEXT,
ADD COLUMN IF NOT EXISTS "created_by" INTEGER,
ADD COLUMN IF NOT EXISTS "updated_by" INTEGER,
ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "usuario"
ADD CONSTRAINT "usuario_created_by_fkey"
FOREIGN KEY ("created_by") REFERENCES "usuario"("id")
ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "usuario"
ADD CONSTRAINT "usuario_updated_by_fkey"
FOREIGN KEY ("updated_by") REFERENCES "usuario"("id")
ON DELETE SET NULL ON UPDATE CASCADE;
